services:
  api:
    build:
      context: .
      dockerfile: deploy/docker/api.Dockerfile
    environment:
      Cors__AllowedOrigins__0: http://localhost:4200
      Database__Snapshot__BucketName: ""
      Database__Snapshot__LocalPath: /app/data/foton.db
    ports:
      - "8080:8080"
    volumes:
      - foton_sqlite_data:/app/data
    networks:
      default:
        aliases:
          - foton-api

  web:
    build:
      context: .
      dockerfile: deploy/docker/web.Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  foton_sqlite_data:
